name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
        
    - name: Install dependencies
      run: npm install
      
    - name: Run tests
      run: npm test

    - name: Super-Linter
      uses: super-linter/super-linter@v5.6.1
  